polileg:
	ghdl -a --std=08 polilegsc.vhd
	ghdl -a --std=08 polilegsc_tb.vhd
	ghdl -r --std=08 polilegsc_tb --wave=polileg.ghw

polilegv2:
	ghdl -a --std=08 polilegscv2.vhd
	ghdl -a --std=08 polilegsc_tb.vhd
	ghdl -r --std=08 polilegsc_tb --wave=polilegv2.ghw

rom:
	ghdl -a --std=08 rom.vhd
	ghdl -a --std=08 rom_tb.vhd
	ghdl -r --std=08 rom_tb --wave=rom.ghw
