alu1bit:
	ghdl -a --std=08 alu1bit.vhd
	ghdl -a --std=08 alu1bit_tb.vhd
	ghdl -r --std=08 alu1bit_tb --wave=alu1bit.ghw

alu:
	ghdl -a --std=08 alu.vhd
	ghdl -a --std=08 alu_tb.vhd
	ghdl -r --std=08 alu_tb --wave=alu.ghw