async:
	ghdl -a mmc_async.vhd
	ghdl -a mmc_tb.vhd
	ghdl -r mmc_tb --vcd=mmc.vcd

sync:
	ghdl -a mmc_sync.vhd
	ghdl -a mmc_tb.vhd
	ghdl -r mmc_tb --vcd=mmc.vcd

mmc3:
	ghdl -a mmc_3.vhd
	ghdl -a mmc_tb.vhd
	ghdl -r mmc_tb --vcd=mmc.vcd

mmc4:
	ghdl -a mmc_4.vhd
	ghdl -a mmc_tb.vhd
	ghdl -r mmc_tb --vcd=mmc.vcd

tbv6:
	ghdl -a mmc_async.vhd
	ghdl -a tb_v6.vhd
	ghdl -r testbench --vcd=mmc.vcd
	