signextend:
	ghdl -a --std=08 signExtend.vhd
	ghdl -a --std=08 signExtend_tb.vhd
	ghdl -r --std=08 signExtend_tb --wave=signExtend.ghw

alu:
	ghdl -a --std=08 alu.vhd
	ghdl -a --std=08 alu_tb.vhd
	ghdl -r --std=08 alu_tb --wave=alu.ghw